### ISSUE TITLE
Feature request - Scaled Position

### ISSUE THREAD

**Issue by Fortune95** [Rintrium/ioBroker.selverf#10]
Is it possible to scale the objects position and target position from 0 to 100%? Zero is closed and hundred are fully open?

**Comment by Rintrium** [comment]
I can add that with the next version. There are also still some bugs in the reconnection mechanism when the gateway sends invalid data or can't be reached, which I hope to fix too

**Comment by Rintrium** [comment]
Scaled position is added in version 0.3.4. As 0 is specified as fully opened by Selve the scaled position also has 0 as open and 100 as fully closed blinds.
