### ISSUE TITLE
Update stable version in repo from 0.6.2 to 0.6.3

### ISSUE THREAD

**Issue by GermanBluefox** [Rintrium/ioBroker.selverf#191]
# Think about update stable version to 0.6.3
**Version**: stable=**0.6.2** (366 days old) => latest=**0.6.3** (15 days old)
**Installs**: stable=**35** (87.5%), latest=**5** (12.5%), total=**40**
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L1966)

**Comment by mcm1957** [comment]
A kind reminder.
Is there any reason to delay an update of stable revision?

Feel free to drop a simple note if I should trigger an update.

**Comment by mcm1957** [comment]
@Rintrium 
Is there any reason to delay updating stable any longer?
Please drop a commit if you know any reason to refrain from updating.

**If there is no response within the next 30 days, we could decide to update anyway.**

**Comment by Rintrium** [comment]
@mcm1957 

I bumped the version and made the pull request [here](https://github.com/ioBroker/ioBroker.repositories/pull/2758#issue-1943532748).
If there are any necessary changes to the adapter I can't guarantee being able to make them soon, since I don't have enough free time for that.
